export const ROUTES = [
  { origin: "Acajutla SV (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Acajutla SV (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Arica CL (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Arica CL (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Arica CL (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Arica CL (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Belawan ID (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Belawan ID (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Belawan ID (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Belawan ID (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Belawan ID (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Belawan ID (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Aarhus DK (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Belfast GB (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Jeddah CY SA (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Los Angeles US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "New Orleans US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "New York US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Buenaventura CO (SeaPort)", destination: "Seattle US (SeaPort)" },
  { origin: "Caldera CR (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Jacksonville US (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Cartagena CO (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Conakry GN (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Jacksonville US (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Corinto NI (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Dar Es Salaam TZ (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Dili TL (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Dili TL (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Dili TL (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Amsterdam CY NL (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Jacksonville US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Jeddah CY SA (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Los Angeles US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Montreal CA (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "New York US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Djibouti DJ (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Guayaquil EC (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Guayaquil EC (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Guayaquil EC (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Haiphong VN (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Ho Chi Minh City VN (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Ho Chi Minh City VN (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Mangalore IN (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Mangalore IN (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Mangalore IN (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Mangalore IN (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Mangalore IN (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Manila PH (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Manila PH (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Manzanillo PA (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Moin CR (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Moin CR (SeaPort)", destination: "New Orleans US (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Amsterdam CY NL (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Belfast GB (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Jacksonville US (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Jeddah CY SA (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Montreal CA (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "New York US (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Mombasa KE (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Copenhagen DK (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Jeddah CY SA (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Paita PE (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Puerto Barrios GT (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Puerto Cabello VE (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Puerto Cabello VE (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Aarhus DK (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Jacksonville US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Los Angeles US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Montreal CA (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Puerto Cortes HN (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "New York US (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Puerto Limon CR (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Quetzal GT (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Rodman PA (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Belfast GB (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Charleston US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Copenhagen DK (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Jacksonville US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Jeddah CY SA (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Los Angeles US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Santos BR (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Aarhus DK (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Barcelona CY ES (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Houston US (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Santo Tomas GT (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Semarang ID (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Antwerp CY BE (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Belfast GB (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Bremen SD DE (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Hamburg CY DE (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Le Havre CY FR (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "London Gateway CY GB (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Los Angeles US (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Newark US (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Oakland US (SeaPort)" },
  { origin: "Vera Cruz MX (SeaPort)", destination: "Rotterdam CY NL (SeaPort)" },
  { origin: "Vitoria BR (SeaPort)", destination: "New York US (SeaPort)" }
];